### ISSUE TITLE
Event edit in books crash

### ISSUE THREAD

**Issue by TabFox-log** [mega12345mega/NBT-Editor#114]
When writing a book, if you try to add a "when hovered" event, it needs quotes if it has space characters in it. When trying to edit text with one of these events, the game just crashes. 
Version: 1.20.1
I don't know if it still is a bug

**Comment by mega12345mega** [comment]
I fixed [Issue #91](https://github.com/mega12345mega/NBT-Editor/issues/91) a little bit ago, so you should probably check if the latest version has this crash

The text input expects JSON text, which is why spaces don't work. I should change it to use the special text format (depending on the config entry), which is more intuitive and fixes this

**Comment by TabFox-log** [comment]
Alright, it probably doesn't crash then. I'll check.
