### ISSUE TITLE
Stay inside the mods folder

### ISSUE THREAD

**Issue by simonbison01** [mega12345mega/NBT-Editor#12]
Hello authors of NBT-Editor,

please stop clogging up the .minecraft folder and stay inside .minecraft/mods/nbteditor

Thanks

**Comment by mega12345mega** [comment]
I'm not sure what you're talking about; the only thing it creates outside of the mods folder is the `nbteditor` folder. This is because I've never seen a mod save its information inside the mods folder, while I have seen them save information in the game directory.

Here are some other folders/files in the game directory from mods I used or am using:
```
.optifine/ (from OptiFabric, which I no longer use)
.replay_cache/
replay_recordings/
schematics/
XaeroWaypoints/
XaeroWaypoints_BACKUP032021/
XaeroWorldMap/
optionsof.txt (from OptiFabric, which I no longer use)
```

Technically, the `shaderpacks` folder and `optionsshaders.txt` file are both for the Iris mod as well.

I thought that I would stay with how all the other mods seem to store their information, instead of putting it in the mods folder, which might confuse people.

I don't believe I have any other folders/files in the game directory other than `nbteditor`, so I'm a bit confused. If there are any other files in the game directory that appears to be from my mod, please notify me, since they are definitely not supposed to be there - though I'm not seeing any myself.

I usually separate my different mods and versions into other game directories, rather than `.minecraft`.
For example:
```
Desktop/Forge/1.8.9/
Desktop/Forge/1.12.2/
etc.
Desktop/Fabric/1.16.5/
Desktop/Fabric/1.18.2/
Desktop/Fabric/1.19.0/
etc.
```

That helps cleanup the `.minecraft` folder, and makes it easier to start the game with different mods.
Hopefully that helps?

**Comment by mega12345mega** [comment]
Do you have any questions, or should I go ahead and close this issue?

**Comment by simonbison01** [comment]
Thank you for your answer. It is not a problematic issue. Close as suggested.

**Comment by HyperSoop** [comment]
@mega12345mega it could be beneficial to move from the .minecraft root folder to .minecraft/config, that's pretty much the place one would expect mods' data to be stored
