### ISSUE TITLE
Bug: nbteditor-2.0.2.999 is incompatible with yesstevemodel-fabric-1.21-2.2.2.jar

### ISSUE THREAD

**Issue by zhjc2021** [mega12345mega/NBT-Editor#124]
mc version:1.21
mod list:
![image](https://github.com/user-attachments/assets/78a30ac0-12e1-4285-98c4-796b08c1b3b5)

crash view:
![f16a6460b671ed5c73ac0a090e853e27](https://github.com/user-attachments/assets/b47146be-22d4-47b2-ad37-6ec86317c141)

crash report:
[minecraft-exported-crash-info-2024-09-28T20-22-27.zip](https://github.com/user-attachments/files/17174416/minecraft-exported-crash-info-2024-09-28T20-22-27.zip)

yesstevemodel official site:
https://modrinth.com/mod/yes-steve-model

meanwhile i have test that nbteditor-2.0.1 is compatible with yesstevemodel-fabric-1.20-2.2.2 in MC1.20.1

is there some bugs in nbteditor-2.0.2.999?

**Comment by zhjc2021** [comment]
“it seems like the newest version of nbteditor makes some changes in rendering thread”the author of yesstevemodel said

**Comment by mega12345mega** [comment]
Due to the closed-source nature of that mod, it is very difficult to figure out what is actually causing this problem. Unless the mod author can point to the specific problem beyond "the crash happened on the rendering thread," it is not straightforward to fix this without knowing what the mod is actually doing.
Considering I'm against closed source Minecraft mods (especially ones that are free as there is no reason they should be closed source unless their doing something suspicious), I'm not particularly inclined to prioritize this. The combination of effort being put in to actively stop reverse engineering (obfuscation & VMP) and a warning about antivirus is concerning enough that I'd rather not download the mod myself without a good reason.

**Comment by zhjc2021** [comment]
GOOD NEWS This incompatibility has disappeared in the new version NBT Editor v2.0.2
