### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by 123d255** [mega12345mega/NBT-Editor#22]

**Comment by mega12345mega** [comment]
I'm not sure how to help you; I need more information:

What doesn't work?
What version of the mod are you using?
What version of Minecraft are you using?
Are you using Forge or Fabric?
Do you have a crash report or log you can provide?
What other mods are you using? Does removing all the mods except NBT Editor and Fabric API work?

I can't really solve the issue if I don't know what the issue is.

**Comment by 123d255** [comment]
1.it just doesn't show up
2.1.4.0 , 1.5.0 ,1.8.0
3. 1.18.2 1.19
4.forge
5.no
6.
i used the forge and this fabric mod and
 so it didn't work. Could you create for the forge as well

**Comment by mega12345mega** [comment]
I'm not planning on supporting Forge anytime soon, as I would have to maintain multiple versions of the same mod, making the updates take longer. Sorry :/
