### ISSUE TITLE
Chat limit extension still doesn't work

### ISSUE THREAD

**Issue by HyperSoop** [mega12345mega/NBT-Editor#35]
This appears to be a continuation of #26 ; commands get truncated no matter whether they are client side or not

**Comment by mega12345mega** [comment]
I've confirmed this affects 1.19.3 specifically. This isn't directly related to 26, in the sense that 26 had to do with a change in the behavior of the `mouseClicked` method. After looking through the decompiled code, it appears that this is caused by an extra check for the length of the message before sending, which wasn't there previously.

**Comment by mega12345mega** [comment]
I've just released v1.11.0, which fixes this!
<details>
<summary></summary>

Hopefully 1.19.4 isn't as buggy! :)
I spent a bunch of extra time testing stuff.
</details>
