### ISSUE TITLE
mod not working in hardcore worlds

### ISSUE THREAD

**Issue by coolmer1** [mega12345mega/NBT-Editor#44]
tried using the mod's HDB feature in a hardcore world, but heads placed would immediately disappear. even tried enabling LAN cheats and going into creative, still didnt work

**Comment by mega12345mega** [comment]
The HDB in survival mode wouldn't work well, since it would just create a ghost item. However, it should work in creative mode just fine.
I opened up a new hardcore world in 1.19.4, enabled cheats, entered creative, and then was able to successfully place the heads.
When you went into creative mode, did you place the item you had gotten in survival? Entering creative won't fix the ghost item until you click on it while in your inventory. This "clicking" on the item is done automatically when you get the item while in creative, but can't work in survival.
If that isn't the issue, what version are you using? Do you have any other mods loaded?

**Comment by coolmer1** [comment]
using version 1.11.0 for MC ver 1.19.2. i was under the assumption it would work as long as you had cheats or creative on first, but if it doesnt work in survival at all then that might be it. i was hoping to use the hdb without having to use commands to make it feel less cheaty. is there a config file option to make it work in survival?

**Comment by mega12345mega** [comment]
There is not currently a config option to make item modification/creation/deletion work properly in survival, since this mod was mainly designed with map makers and OP items in mind. If I were to add a config option, it would probably make the most sense for it to also allow retrieving items from the client chest, editing items, using the item factories, etc. (This would and can only work in singleplayer worlds.)

Should I add a config option? And should I make it so you can enable the HDB specifically without enabling the other features?
I could make it so you can "transform" other types of heads into ones from the HDB so it isn't free blocks and you have to work a bit for them. I don't know if that is too far from the NBT Editor concept though.

**Comment by HyperSoop** [comment]
> There is not currently a config option to make item modification/creation/deletion work properly in survival, since this mod was mainly designed with map makers and OP items in mind. If I were to add a config option, it would probably make the most sense for it to also allow retrieving items from the client chest, editing items, using the item factories, etc. (This would and can only work in singleplayer worlds.)
> 
> Should I add a config option? And should I make it so you can enable the HDB specifically without enabling the other features? I could make it so you can "transform" other types of heads into ones from the HDB so it isn't free blocks and you have to work a bit for them. I don't know if that is too far from the NBT Editor concept though.

Don't do that. This is supposed to be a client-side mod, after all.

**Comment by coolmer1** [comment]
> There is not currently a config option to make item modification/creation/deletion work properly in survival, since this mod was mainly designed with map makers and OP items in mind. If I were to add a config option, it would probably make the most sense for it to also allow retrieving items from the client chest, editing items, using the item factories, etc. (This would and can only work in singleplayer worlds.)
> 
> Should I add a config option? And should I make it so you can enable the HDB specifically without enabling the other features? I could make it so you can "transform" other types of heads into ones from the HDB so it isn't free blocks and you have to work a bit for them. I don't know if that is too far from the NBT Editor concept though.

I don't think adding a config is necessary. Thank you for clarifying how exactly the feature works :) Sorry to take up your time
