### ISSUE TITLE
Crashes My Game

### ISSUE THREAD

**Issue by EstlyCodes** [mega12345mega/NBT-Editor#53]
I'm trying to load NBT-Editor in 1.19.4 but it keeps crashing my game. I tried every other version and it works but for some reason it doesn't work for 1.19.4

**Comment by mega12345mega** [comment]
I'm going to need the crash report to be able to help. Can you send that file?
Additionally, are you using any other mods (except fabric-api, which is required)? Does it work when those other mods are removed?
Thanks.

**Comment by EstlyCodes** [comment]
Here is the crash report. 
[latest.log](https://github.com/mega12345mega/NBT-Editor/files/11794086/latest.log)

Also, from what I have tried on the official minecraft launcher, it was worked without my other mods but that was on the launcher. This is happening on feather client.

**Comment by mega12345mega** [comment]
I believe this is the same as Issue #46, which (should) be fixed in the next update. I haven't officially tested it, but unrelated changes I have made to the version system should completely bypass the error.
It is interesting that it worked for you with the normal launcher, while it doesn't seem to have worked for the other user.

**Comment by mega12345mega** [comment]
If you could test that v1.12.0 works for you, that would be great! I'm going to close the issue now, since I've just released the update.
