### ISSUE TITLE
on 1.12 keep getting same error 

### ISSUE THREAD

**Issue by L1ghtn1ng-cmd** [mega12345mega/NBT-Editor#54]
Cannot invoke "com.mojang.brigadier.CommandDispatcher.execute(String, Object)" because "com.luneruniverse.minecraft.mod.nbteditor.multiversion.commands.ClientCommandInternals.activeDispatcher" is null

this appears in chat and the commands do not work. i am using client commands - did not show this error before i updated

**Comment by mega12345mega** [comment]
Can you send:
- The Minecraft version
- The client commands version
- The full stacktrace or crash log
- Which command you're running

I'm assuming its the clientcommands commands that don't work, while the NBT Editor ones work fine?

Thanks!

**Comment by mega12345mega** [comment]
Since I've not gotten any more information, and the mod seems to work with the clientcommands mod fine after [Issue #51](https://github.com/mega12345mega/NBT-Editor/issues/51), I'm going to close this. If it still occurs, please create a new issue (I don't believe Github allows you to reopen issues not closed by you for some reason).
