### ISSUE TITLE
Incompatibility with labymod 4

### ISSUE THREAD

**Issue by nick22985** [mega12345mega/NBT-Editor#57]
Hey,
As this is related to labymod 4 it might not be able to be fixed by you / might have to be fixed by laby. But if it could be would be much appreciated.

https://paste.labymod.net/ojowewegiv

**Comment by mega12345mega** [comment]
This crash is very strange. Long story short, I don't think I'll be able to fix this, especially without any experience with Labymod. I didn't find a Github, and it appears that the Labymod website has a special way to report bugs. I don't know if there is a special system for beta testers of 4, since it doesn't appear to be released yet. You might be interested in sending them a link to this issue, though I'm guessing it would be very difficult to fix on their end too, especially considering they're trying to load Forge and Fabric mods at the same time. Here are the details:

The error that is spammed in the log refers to the enchantment display feature. It appears that the config value for how to display enchantments isn't loaded. Looking further down, it seems there is a second exception, which occurs before the config is loaded, causing this issue. It seems like Labymod should have crashed at this point, rather than continuing while the NBT Editor mod is in a "corrupted" state. (Can you specify when the game crashed?) It is possible that it attempted to continue loading without the NBT Editor mod, but forgot to undo the mixins (if that is even possible).

The exception that I identified as the source of the issue seems to indicate that class `org.joml.Matrix4f` doesn't exist. This doesn't make sense, since Minecraft 1.19.4 is supposed to have switched to this Matrix library. This difference in expectation vs reality throws an exception.

There is also another exception on line 352 of the log. Did you attempt to open NBT Editor's config menu? This issue would also be caused by the `Matrix4f` exception.

Finally, the stacktrace seems to be using fully obfuscated class names. I don't know if Labymod has a special way to make it work, but due to the `remap = false` in several of my mixins and how I assume intermediary mappings in a lot of my code, I wouldn't be surprised if there were lots of other issues relating to this as well.

**Comment by nick22985** [comment]
It crashes as soon as you open your inv. 

Also /nbt says unknown command the error that occurs.

Yea, I assume it is 100% laby related and only they will be able to fix it. Fabric support is experimental atm was just taking a shot in the dark just incase. Thank you

**Comment by AroPix** [comment]
I still have issues with Labymod, when i join a server or world its just stuck in the loading screen on Joining World making this mod unusable with Laby :/

**Comment by mega12345mega** [comment]
This issue wasn't ever fixed, as it would be extremely complicated - in other words, I don't support Labymod
