### ISSUE TITLE
ClientChest Improvements

### ISSUE THREAD

**Issue by KadTheHunter** [mega12345mega/NBT-Editor#60]
I've thought of a few improvements for the ClientChest:

- The `/clientchest` command should accept numerical arguments to allow users to open a specific page (e.g `/clientchest 3` would open page 3
- The ability to name pages; Not sure if this one is even possible, but ideally it would be done via another button or dialog box on the left
- Hotkeys (or keybinds) to navigate within the ClientChest; Currently you can *kinda* use the arrow keys or tab to select a button, and then hit enter to click it, but it would be great if at least the Left/Right arrow keys moved the pages.

**Comment by mega12345mega** [comment]
These sound great! They shouldn't be too difficult to implement. As a combination of 1 and 2, `/chest <name>` would also work (and should suggest the different names as you are typing).

Similar to the book editor, I could use the Page Up and Page Down buttons. I may add a config option for using arrow keys for users with smaller keyboards.

This does lead into a more folder structure; when you start having lots of weapons in the "weapons" page, you might want a "weapons/swords", "weapons/bows", etc. However I don't know a good way to add this in the gui. It is probably too extreme (at least for now).

In the meantime, named containers work great for sorting things (and they can be nested!). The main disadvantage is that they usually have 27 slots instead of 54. You can use the keybind to open the containers without bringing them out of the chest.

**Comment by KadTheHunter** [comment]
Just tried the dev build, and it works great! Everything is as I hoped. Only things I noticed is:
- Page Down increases the page number and Page Up decreases it-- not sure if that's intended, or if it got swapped lol
- Using a page name twice unnames the earlier instance of it; If possible I think it should warn you there's another page with that name, if not prevent you from using a name twice.
  - Not sure how duplicate names could be allowed other than suffixing them with a number, and adding page or name numbers both seem to defeat the point, so... yeah just a warning or prevention for duplicates is probably enough.
  
Regardless, amazing work, and thank you so much for adding this :D

**Comment by mega12345mega** [comment]
When writing the page keybind code, I was thinking of Page Down as a sort of next page, since you would typically type it when you want to see the next piece of text on a website. Do you think this should be configurable?

I've now changed it so that when you type a duplicate name it highlights it in red (just like when entering an invalid value in the item factories), but hitting Enter causes it to override.

**Comment by KadTheHunter** [comment]
> When writing the page keybind code, I was thinking of Page Down as a sort of next page, since you would typically type it when you want to see the next piece of text on a website. Do you think this should be configurable?

I was thinking of it more as a Forward/Backward, where Page Up would increase the page number and Page Down decreases it. Probably would be best if the keybind was configurable, but now that I know what you were going for it makes more sense.

> I've now changed it so that when you type a duplicate name it highlights it in red (just like when entering an invalid value in the item factories), but hitting Enter causes it to override.

Just tested it, works perfect, thanks!

**Comment by mega12345mega** [comment]
I've now released this in v1.13.0!
