### ISSUE TITLE
Using in survival without op

### ISSUE THREAD

**Issue by MrYaronKa** [mega12345mega/NBT-Editor#61]

**Comment by HyperSoop** [comment]
That'd be beyond the scope of the mod, as it's supposed to be client-side.

**Comment by mega12345mega** [comment]
This relates to Issue #55, where I mention that I could make it where the mod could be *optionally* loaded on the server to add additional features that would normally be impossible.

Non-op survival is especially interesting however, since it implies that (when being used on a server) any user would be able to have effectively creative mode. It would probably be best to use permissions in this case. However, this wouldn't be super high priority, since as @HyperSoop mentions, the mod is client focused.

**Comment by mega12345mega** [comment]
I've now released editing in survival *with* op in v2.0.0. I will not add editing *without* OP, as this would immediately allow you to op yourself by creating pre-placed command blocks.
