### ISSUE TITLE
Cannot Load Minecraft with NBTEditor

### ISSUE THREAD

**Issue by toadwaawa** [mega12345mega/NBT-Editor#85]
Basically, when I run Minecraft it gives me an error (listed down below:)

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
More details:
	 - Mod 'NBT Editor' (nbteditor) 1.12.3 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I tried changing from 1.20.4 to 1.20.2 and I even had meteor and it didnt work. I don't know what it means by "Install Fabric, Any version" when I already have it installed. Please help

**Comment by mega12345mega** [comment]
I'm not completely sure what this means, but my best guess is that you need to install [Fabric API](https://modrinth.com/mod/fabric-api), which is a standard API for almost every fabric mod. That said, I would expected something like "Install fabric-api, any version" instead of just "fabric", so I'm not sure. If you tested with only Meteor Client, then that is probably the issue.

**Comment by toadwaawa** [comment]
I removed meteor and tried it without that. It didn't work, it gave me the same error

**Comment by toadwaawa** [comment]
Hm the fix seems to be Fabric API - I didn't have it before and it seems like it fixed it
(I didn't know what Fabric API is)
